Variable Cost Refactor Part 1: Function Data
NREL-Sienna/PowerSystems.jl pull request #1056
Opened 2024-02-16 00:12 UTC by GabrielKS

The first part of a significant refactor of Sienna cost data structures. Relates to https://github.com/NREL-Sienna/PowerSystems.jl/issues/934, https://github.com/NREL-Sienna/PowerSystems.jl/issues/985, https://github.com/NREL-Sienna/PowerSystems.jl/issues/1007.

At the time of draft PR creation, all tests pass except for these:
  * `Test field validation` in `test_validation.jl`: an issue unrelated to these changes, a fix will become available on `psy4` soon and I'll rebase onto that
  * Several tests in `test_cost_functions.jl`: waiting on a decision about whether to refactor aspects of InfrastructureSystems (e.g., the `Deterministic` struct)

…provided that [this commit](https://github.com/NREL-Sienna/PowerSystemsTestData/tree/7910da87f7749f1baa17286315542bc593e16605) of PowerSystemsTestData is used (by changing the PowerSystemsCaseBuilder `DATA_DIR` to a local clone of that).

This is not quite ready for full review but I'm putting it out here to track progress.

2024-02-16 18:12 UTC, jd-lara commented on src/PowerSystems.jl
> +export get_proportional_term, get_quadratic_term, get_constant_term, get_coefficients
```suggestion
export get_proportional_term 
export get_quadratic_term 
export get_constant_term 
export get_coefficients
```

2024-02-16 18:14 UTC, jd-lara commented on src/parsers/power_system_table_data.jl
> +    var_cost = PiecewiseLinearPointData([(x, y) for (y, x) in var_cost])
Formatter run missing

2024-02-16 18:15 UTC, jd-lara commented on test/test_cost_functions.jl
> +# TODO figure out how to handle costs in InfrastructureSystems
This is more about the implementation of MarketBidCost that anything else.

2024-02-16 18:32 UTC, GabrielKS commented on src/PowerSystems.jl
> +export get_proportional_term, get_quadratic_term, get_constant_term, get_coefficients
Done

2024-02-16 18:34 UTC, jd-lara requested changes
After an offline conversation, the decision is to move the code for FunctionData to IS and re-export in PSY. 

Implement that change in this PR prior to merging.

2024-02-20 19:40 UTC, GabrielKS commented
Rebased on top of https://github.com/NREL-Sienna/PowerSystems.jl/pull/1057

2024-02-20 20:35 UTC, GabrielKS commented
Never mind about https://github.com/NREL-Sienna/PowerSystems.jl/pull/1057, it was a bad idea. All those changes are here.

2024-02-22 09:38 UTC, GabrielKS commented
Finally ready for review! Now that the FunctionData structs live in InfrastructureSystems, this PR is mostly adapting existing cost data structures to use the new ones, plus System JSON conversion code.

IS, PSY, and PSB tests pass when using the appropriate branches of each plus PowerSystemsTestData:
<img width="1616" alt="Screenshot of passing tests" src="https://github.com/NREL-Sienna/InfrastructureSystems.jl/assets/23368820/ebb41c4c-f701-4109-9fb2-109e594522a9">

2024-02-22 09:40 UTC, GabrielKS commented
The group of four PRs this is a part of:

1. https://github.com/NREL-Sienna/InfrastructureSystems.jl/pull/331
2. https://github.com/NREL-Sienna/PowerSystems.jl/pull/1056
3. https://github.com/NREL-Sienna/PowerSystemCaseBuilder.jl/pull/72
4. https://github.com/NREL-Sienna/PowerSystemsTestData/pull/50

2024-02-22 20:46 UTC, jd-lara approved these changes

2024-02-22 20:46 UTC, merged