fix: Adding support for quadratic functions using the table data parser
NREL-Sienna/PowerSystems.jl pull request #1178
Opened 2024-08-26 23:23 UTC by pesap

Currently only works for heat rate and not cost curves.

Implementation details:

- Added new fields for generators to capture quadratic heat rate curve. For simplicity, the names are `heat_rate_a0`, `heat_rate_a1`, `heat_rate_a2`. Open to suggestions,
- If any `heat_rate_a*` column is defined, then we call `create_poly_cost`,
- `create_poly_cost` will Return either `QuadraticCostCurve` 
  - if exactly three `heat_rate_a*` are found, assuming that `a2` is the quadratic coefficient, `a1` the proportional term and `a0` intercept. 
  - if two matches, we return `LinearCurve using `a1`, `a0`,
  - if one matches, we return `LinearCurve` using `a0`.

Caveats:
- people can pass `a2` only and the code will run but use it as `a0`

Closes #1177

2024-08-26 23:32 UTC, rodrigomha commented on src/parsers/power_system_table_data.jl
> +        @warn cost_colnames
I guess we should give a proper warning? Or remove it?

2024-08-26 23:32 UTC, rodrigomha commented on src/parsers/power_system_table_data.jl
> +    @warn typeof(gen)
Ditto

2024-08-26 23:36 UTC, rodrigomha commented on src/parsers/power_system_table_data.jl
> +    #   3. If two then data is looking like: c
This note should say something like:
```
# Three supported cases,
#   1. If three values are passed then we have data looking like: a * x^2 + b * x + c,
#   2. If two then data is looking like: a * x + b
#   3. If two then data is looking like: a * x
```

2024-08-26 23:37 UTC, rodrigomha requested changes
Remove or update the warnings and update briefly the docs

2024-08-26 23:42 UTC, pesap commented
> Remove or update the warnings and update briefly the docs

This has been addressed.

2024-08-27 00:14 UTC, GabrielKS requested changes

2024-08-27 00:59 UTC, rodrigomha approved these changes

2024-08-27 01:00 UTC, GabrielKS approved these changes

2024-08-27 16:47 UTC, rodrigomha approved these changes

2024-08-27 17:06 UTC, GabrielKS requested changes
Looks good aside from the typo

2024-08-27 17:06 UTC, GabrielKS commented on test/test_power_system_table_data.jl
> +    # Coefficients for a CC using natura gas
```suggestion
    # Coefficients for a CC using natural gas
```

2024-08-27 17:24 UTC, GabrielKS approved these changes

2024-08-28 20:38 UTC, merged