[WIP] Add 2t line physical model
NREL-Sienna/PowerSystems.jl pull request #1205
Opened 2024-10-21 23:48 UTC by rodrigomha

WIP for working in PSI

2024-11-04 23:53 UTC, rodrigomha commented
@jd-lara this is ready for review

2024-11-04 23:55 UTC, jd-lara commented on src/models/generated/TwoTerminalHVDCDetailedLine.jl
> +    mutable struct TwoTerminalHVDCDetailedLine <: ACBranch
Why not re-use the VSC existing structure?

2024-11-08 10:01 UTC, jd-lara commented on src/PowerSystems.jl
>  export TwoTerminalVSCDCLine
Add a comment that this will be dropped in PSY 5.0 please.

2024-12-16 23:19 UTC, rodrigomha commented
This is ready for review @jd-lara 
We need to merge this to get testing passing in our PSI branch of 2T physical models.

2025-01-13 17:04 UTC, jd-lara requested changes
Add code here that reads from PSSe the VSC data and puts into the struct

2025-01-28 21:09 UTC, closed without merging