Parse missing sw shunt data in psse.jl file
NREL-Sienna/PowerSystems.jl pull request #1230
Opened 2024-12-17 19:00 UTC by mcllerena

Adding missing parameters "VSWHI" (upper_limit), "VSWLO" (lower limit), Bi (admittance increment) & Ni (number of steps), to the function _psse2pm_shunt!.

2024-12-17 19:06 UTC, jd-lara requested changes
We need to add a new key to distinguish between fixed and switch shunts too

2024-12-18 21:58 UTC, mcllerena commented on src/parsers/pm_io/psse.jl
> +    @info "Parsing PSS(R)E Shunt data into a PowerxModels Dict..."
Sorry, a misstep on the keyboard. I've already fix it.

2024-12-26 19:35 UTC, jd-lara commented
@mcllerena you need to run the formatter

2024-12-26 19:36 UTC, jd-lara requested changes
@mcllerena this looks good to me. We need to add a case for testing this code and also add the code to read this data into the SwtichedShunt structure.

2025-01-13 17:03 UTC, jd-lara requested changes
We need to add here the code that puts the PM data into the SW shunt struct too.

2025-01-13 17:03 UTC, jd-lara commented
@GabrielKS please confirm that we can export to PSSe too please

2025-01-23 21:49 UTC, GabrielKS reviewed
Reviewing at the newer version https://github.com/NREL-Sienna/PowerSystems.jl/pull/1252

2025-01-23 21:49 UTC, GabrielKS commented on src/models/generated/SwitchedAdmittance.jl
> +        number_of_steps::Union{Int, Vector{Int}}
Why do we need both `Int` and  `Vector{Int}`?

2025-01-24 04:54 UTC, jd-lara commented on src/models/generated/SwitchedAdmittance.jl
> +        number_of_steps::Union{Int, Vector{Int}}
I think I originally added this to enable contingencies x time steps. We can bring it to Vector Int.

2025-01-24 04:54 UTC, jd-lara commented on src/models/generated/SwitchedAdmittance.jl
> +        number_of_steps::Union{Int, Vector{Int}}
I think that PSSe has both options

2025-01-24 18:50 UTC, rodrigomha commented
Closing as being addressed with 3W-XFRM in #1252

2025-02-05 16:15 UTC, closed without merging